export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const LOADING = "LOADING";
export const UPDATE_ARTICLES = "UPDATE_ARTICLES";
export const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";
